language: r
dist: trusty
bioc_required: true
services:
  - docker
cache: packages
warnings_are_errors: true
before_install:
  - source <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
install:
 - use_dynverse_devel
 - install_github_withdeps dynwrap
 - install_withdeps
after_success:
 - R -e 'covr::codecov()'
