language: r
dist: trusty
bioc_required: true
services:
  - docker
cache:
  directories:
    - $HOME/R/Library
warnings_are_errors: true
before_install:
  - source <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
  - install_hdf5
install:
 - use_dynverse_devel
 - install_cran devtools covr
 - install_withdeps
after_success:
 - R -e 'covr::codecov()'
